#!/bin/sh

set -e ;
set -u ;

docker run --rm -it \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v $(pwd)/src:/ansible/playbooks \
  -v /var/log/ansible/ansible.log \
  docker-image "$@"